### ISSUE TITLE
clenup.sh not working

### ISSUE THREAD

**Issue by stefanogg** [jperkel/conda-env-tests#4]
Hi, thank you for putting together this nice example of the impact of programming environments. I just wanted to flag that the `clenup.sh` script didn't work on my laptop. The reason: the `cut` option `-w` is not supported. I replaced it with `-d '  '`

**Comment by jperkel** [comment]
Thank you, @stefanogg, good tip. Fixed with [`55f4cd6`](https://github.com/jperkel/conda-env-tests/commit/55f4cd6ddc07a746fa5b534f16f7fd8d93f2da7d).
